In [1]:
import numpy as np 
import pandas as pd

### Creating a DataFrame

In [92]:
data= {
    'Name':['John','Anna','Peter','Linda'],
    'Age':[28,34,29,42],
    'City':['New York','Paris','Berlin','London'],
    'Salary':[65000,70000,62000,85000]
}
df=pd.DataFrame(data)

df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [31]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2=pd.DataFrame(data_list)

In [32]:
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [62]:
#creating columns name
columns=["Name","Age","City","Salary"]
df2=pd.DataFrame(data_list,columns=columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

### Selection and Indexing of Columns

In [34]:
df2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [35]:
df2['Age']

0    28
1    34
2    29
3    42
Name: Age, dtype: int64

In [60]:
df2[["Name","Age"]]

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

### Creating a new Columns

In [84]:
df2["Designation"]=["Doctor","Engg.","Doctor","Engg."]
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000       Engg.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000       Engg.

### Removing Columns

In [85]:
#tempory data delete
df2.drop(['Designation'],axis=1)
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000       Engg.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000       Engg.

In [86]:
#permentaly delete data 
df2.drop('Designation',axis=1,inplace=True)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [79]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [87]:
#temporary delete 
df2.drop(['Age','City'],axis=1)

    Name  Salary
0   John   65000
1   Anna   70000
2  Peter   62000
3  Linda   85000

In [88]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [89]:
#delete row wise data temporary
df2.drop([0,1],axis=0)

    Name  Age    City  Salary
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [90]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

### Selecting Rows

In [99]:
#by rows
df2.loc[2]

Name       Peter
Age           29
City      Berlin
Salary     62000
Name: 2, dtype: object

In [100]:
df2.loc[[0,2]]

    Name  Age      City  Salary
0   John   28  New York   65000
2  Peter   29    Berlin   62000

In [101]:
#by indexing
df2.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

In [102]:
df2.iloc[[0,2]]

    Name  Age      City  Salary
0   John   28  New York   65000
2  Peter   29    Berlin   62000

### Selecting subsets of rows and columns

In [105]:
df2.loc[[0,1]][['City','Salary']]

       City  Salary
0  New York   65000
1     Paris   70000

In [106]:
df2.loc[[2,3]][['Name','Age']]

    Name  Age
2  Peter   29
3  Linda   42

### Conditional Selection

In [108]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
# i want see those people whose age is greater then 30

In [111]:
df2[df2['Age']>30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [ ]:
# i want see only those people whose age is greater then 30 and city must be paris

In [121]:
df2[(df2['Age']>30) & (df2['City'] == 'Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000