In [1]:
import numpy as np 
import pandas as pd

## Finding missing Data

In [11]:
import pandas as pd
import numpy as np

data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [3, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}

df = pd.DataFrame(data)

In [12]:
df

     A  B    C    D
0  1.0  3  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [6]:
df.isna()

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [7]:
df.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

In [8]:
#isna() it check the nan -true, false
df.isna()

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

## Removing missing data

In [13]:
df

     A  B    C    D
0  1.0  3  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [14]:
df.dropna()

     A  B    C    D
0  1.0  3  1.0  1.0

In [19]:
#no of thresh =no of non-null values in row so,that will be printing 
df.dropna(thresh=3)

     A  B    C    D
0  1.0  3  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

## Filling the missing data

In [20]:
df

     A  B    C    D
0  1.0  3  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [21]:
#temporary change
df.fillna(0)

     A  B    C    D
0  1.0  3  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [22]:
df

     A  B    C    D
0  1.0  3  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [25]:
#value assign by using columns name
value={
    'A':0, 
    'B':100, 
    'C':200, 
    'D':300
}
df.fillna(value=value)

     A  B      C      D
0  1.0  3    1.0    1.0
1  2.0  2    2.0  300.0
2  0.0  3    3.0  300.0
3  4.0  4  200.0  300.0
4  5.0  5  200.0    5.0