In [2]:
import pandas as pd 
import numpy as np

## DataFrame Basic Operations

In [3]:
df1=pd.DataFrame({
    'A':[1,2,3,4,5],
    'B':[10,20,30,40,50], 
    'C':[100,200,300,400,500]
})

In [4]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [5]:
df1.shape

(5, 3)

In [7]:
df1.size

15

In [8]:
df1.columns

Index(['A', 'B', 'C'], dtype='str')

In [9]:
df1.info

<bound method DataFrame.info of    A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500>

In [10]:
df1.describe

<bound method NDFrame.describe of    A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500>

In [11]:
df1['A']+10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

## DataFrame applying Functions

In [12]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [13]:
def square(x):
    return x**2

In [16]:
df1['D']=df1['B'].apply(square)
df1

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500